name: Testuj Flask Kalkulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zainstaluj zależności
        run: pip install -r requirements.txt

      - name: Zainstaluj Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Uruchom testy z Allure
        run: pytest --alluredir=allure-results

      - name: Wygeneruj raport Allure
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Załącz raport jako artefakt
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Skonfiguruj Git usera
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pobierz raport Allure
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy do GitHub Pages
        uses: peaceiris/
